2.0.0 and init -upgrade
delphix-integrations/terraform-provider-delphix pull request #63
Opened 2023-06-21 21:38 UTC by nick-mathison

Updating our public docs to align with the working solution.
https://delphix.slack.com/archives/C03LZ2Q3QGG/p1687382977052709

Updates
- Added `-upgrade` to the init command which overwrites any previous TF installations.
- Specified the 2.0.0 provider.

2023-09-25 15:43 UTC, Uddipaan-Hazarika approved these changes
Looks good to me.

2023-11-10 09:53 UTC, elima-sugunan requested changes

2023-11-10 09:53 UTC, elima-sugunan commented on examples/simple-provision/versions.tf
> +      version = "2.0.0"
Should it be updated with latest cersion?

2023-11-15 15:28 UTC, ankit-patil-hubs commented
inclded changes in https://github.com/delphix-integrations/terraform-provider-delphix/pull/72

2023-11-15 15:28 UTC, closed without merging