Main page update
delphix-integrations/terraform-provider-delphix pull request #81
Opened 2024-03-18 18:27 UTC by nick-mathison

Cleaned up the main page.

Points of Note:

Clarified the description
Added System Requirements section that broadly states support across the provider.
Updated the organization of the example script. Mad reference the other documentation.

Original PR: https://github.com/delphix-integrations/terraform-provider-delphix/pull/78

2024-03-19 07:12 UTC, ankit-patil-hubs approved these changes

2024-03-19 15:20 UTC, elima-sugunan requested changes

2024-03-19 15:20 UTC, elima-sugunan commented on docs/index.md
> +      version = "3.1.0"
3.2.0 will be the latest release

2024-03-21 07:39 UTC, elima-sugunan approved these changes

2024-03-21 07:45 UTC, merged